name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: SherlockGUI-Linux
            asset_name: sherlock-gui-linux
          - os: windows-latest
            artifact_name: SherlockGUI-Windows
            asset_name: sherlock-gui-windows.exe
          - os: macos-latest
            artifact_name: SherlockGUI-MacOS
            asset_name: sherlock-gui-macos

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=src/resources/icons/sherlock.ico src/main.py --name ${{ matrix.artifact_name }}
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/${{ matrix.artifact_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}